spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    cloud:
        config:
            import-check:
                enabled: false

    #   TODO: This here should be modified with the conn strings for the DB
    datasource:
        url: jdbc:postgresql://ep-blue-unit-a9sgubnv-pooler.gwc.azure.neon.tech/neondb?user=neondb_owner&password=npg_6uxWRegqfY7C&sslmode=require
        username: neondb_owner
        password: npg_6uxWRegqfY7C
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: 3000